DEV_MODE: user ##user or dev, cambia la autorizacion sobre cosas que se pueden hacer
DEVICE: cpu

MODELS_DIR: ./models

EMBEDDINGS_PATH: all-MiniLM-L6-v2
# EMBEDDINGS_PATH: bge-small-en-v1.5

#VECTORDB_TYPE: faiss
#VECTORDB_PATH: vectordb/faiss
VECTORDB_TYPE: chroma
VECTORDB_PATH: vectordb/chroma

TTS_PATH: src/tmp

USE_CTRANSFORMERS: True
#LLM_PATH: mistral-7b-instruct-v0.2.Q4_K_M.gguf
LLM_PATH: mistral-7b-instruct-v0.2.Q5_K_M.gguf
PROMPT_TYPE: mistral

LLM_CONFIG:
  MAX_NEW_TOKENS: 512
  TEMPERATURE: 0.2
  REPETITION_PENALTY: 1.1
  CONTEXT_LENGTH: 4000

BASE_RETRIEVER_CONFIG:
  SEARCH_K: 4

# RERANKER_PATH: tart-full-flan-t5-xl
# RERANKER_TYPE: tart
RERANKER_PATH: bge-reranker-base
RERANKER_TYPE: bge

RERANK_RETRIEVER_CONFIG:
  SEARCH_K: 10
  TOP_N: 4

COMPRESSION_RETRIEVER_CONFIG:
  SEARCH_K: 10
  SIMILARITY_THRESHOLD: 0.5

TEXT_SPLIT_MODE: default  # default or propositionize
# propositionize uses propositionizer model
CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
SEPARATORS: ["\n\n", "\n", ". ", " ", ""]


PROPOSITIONIZER_PATH: propositionizer-wiki-flan-t5-large
PROPOSITIONIZER_CONFIG:
  CHUNK_SIZE: 1000
  CHUNK_OVERLAP: 0
