dependencies:
- python=3.11.4
- pip=23.2.1
- pip:
  - chromadb==0.4.23
  - ctransformers==0.2.27
  - faiss-cpu==1.7.4
  - langchain==0.1.6
  - langchain-community==0.0.19
  - PyMuPDF==1.23.8
  - python-box==7.1.1
  - rank-bm25==0.2.2
  - sentence-transformers==2.2.2
  - simsimd==3.3.0
  - streamlit==1.31.1
  - transformers==4.38.1
  - umap-learn==0.5.5
  - gtts==2.5.1
  - pygame-ce==2.4.1 
  - soundfile==0.12.1
  - mutagen==1.47.0
  - pygame==2.5.2
  - SpeechRecognition==3.10.3
  - pyttsx3==2.90
  - pyaudio==0.2.14

  #click==8.1.7
